### ISSUE TITLE
date field

### ISSUE THREAD

**Issue by diogobarreto** [hugombarreto/guiabolso2csv#1]
All in all the program works well and I'm very pleased, however, the date field does not download correctly.   For instance, the day 30/06/2017 is downloaded as "1498791600000".  
I've noticed that each date changes by an increment of 86400000, which is the number of seconds in a day multiplied by 1000.  For my data, I managed to identify the date of one transaction and then manage to convert the date for all the other records.  I hope this helps and thanks again for this routine.

**Comment by diogobarreto** [comment]
All in all the program works well and I'm very pleased, however, the date field does not download correctly. For instance, the day 30/06/2017 is downloaded as "1498791600000".
I've noticed that each date changes by an increment of 86400000, which is the number of seconds in a day multiplied by 1000. For my data, I managed to identify the date of one transaction and then manage to convert the date for all the other records. I hope this helps and thanks again for this routine.

**Comment by hsadok** [comment]
Hi Diogo,

I'm glad this is being useful to you. There are a few things missing here and there and I appreciate anytime someone point out.

The time is given in milliseconds since the Epoch, which is a classic time representation on UNIX systems. You can even use python to "decode" it:
`python -c 'import time; print time.ctime(1498791600000/1000)'`

**Comment by diogobarreto** [comment]
Thanks for the quick reply so late at night, this program has been superb, everything I could wish for!  
Hugo, I have calculated that the "1498791600000" number (which refers to 30/06/2017) implies that the system date be: 31/12/1969  21:00:00, does this make sense?
For a future update (in case it's simple to implement), would it be possible to export this date as 42916, which is the number equivalent of 30/06/2017 in Excel?
Thanks in advance!

**Comment by hsadok** [comment]
31/12/1969 21:00:00 is precisely the Epoch in UTC-3 time zone. How did you calculate that?

I'll see if I can convert epoch time to Excel time. Right now I'm really short on time so I'll likely make any change to the code only next month. But you can count on it 😀

**Comment by diogobarreto** [comment]
I just reversed the calculation in milliseconds from a known date in my expenses. :)  Perhaps you could apply a simple query to the date column based upon a know date in Excel's time format and Epoch's, such as: =42916-(1498791600000-X)/86400000,  where X would be the record's date in Epoch.format.
And no worries, the program is already extremely useful and I can always sort these things out through post-processing.  Thanks again and keep up the good work!

**Comment by hsadok** [comment]
I believe this issue is solved when using the new ``--excel`` flag. (https://github.com/hugombarreto/guiabolso2csv/commit/bda95f5c9fadd1ad7bca80b53fd1f0cc832a30eb)

Using this flag, the output is generated directly in a ``xlsx`` format and the date field works as expected.

Check the updated README for further instructions.

**Comment by diogobarreto** [comment]
Yes, Hugo, you are right, this same issue had been solved with the excel export (I did not remember), but as I had an issue with the additional "--" commands and exported as a csv, the issue resurfaced.   Thanks again.
