### ISSUE TITLE
Comando: Intervalo de Meses

### ISSUE THREAD

**Issue by diogobarreto** [hugombarreto/guiabolso2csv#12]
Hugo, 

O uso básico está funcionando (entrando no guiabolso e fazendo o download em csv de um mês específico), mas os comandos mais sofisticados de intervalo de meses volta com o seguinte erro abaixo:

> 

> Traceback (most recent call last):
>   File "c:\program files\python\python37\lib\site-packages\pkg_resources\__init__.py", line 583, in _build_master
>     ws.require(__requires__)
>   File "c:\program files\python\python37\lib\site-packages\pkg_resources\__init__.py", line 900, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "c:\program files\python\python37\lib\site-packages\pkg_resources\__init__.py", line 791, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.VersionConflict: (guiabolso2csv 0.6 (c:\users\diogo.barreto\appdata\roaming\python\python37\site-packages), Requirement.parse('guiabolso2csv==0.5'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Program Files\Python\Python37\Scripts\guiabolso2csv-script.py", line 6, in <module>
>     from pkg_resources import load_entry_point
>   File "c:\program files\python\python37\lib\site-packages\pkg_resources\__init__.py", line 3191, in <module>
>     @_call_aside
>   File "c:\program files\python\python37\lib\site-packages\pkg_resources\__init__.py", line 3175, in _call_aside
>     f(*args, **kwargs)
>   File "c:\program files\python\python37\lib\site-packages\pkg_resources\__init__.py", line 3204, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "c:\program files\python\python37\lib\site-packages\pkg_resources\__init__.py", line 585, in _build_master
>     return cls._build_from_requirements(__requires__)
>   File "c:\program files\python\python37\lib\site-packages\pkg_resources\__init__.py", line 598, in _build_from_requirements
>     dists = ws.resolve(reqs, Environment())
>   File "c:\program files\python\python37\lib\site-packages\pkg_resources\__init__.py", line 786, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'guiabolso2csv==0.5' distribution was not found and is required by the application

Se conseguir dar uma olhada, agradeço imensamente.  Aproveito também para desejar um Feliz 2021!

**Comment by hsadok** [comment]
Isso parece algum conflito de versão na sua máquina. Repara que ele está tentando usar a versão `0.5` ao invés da `0.6`. 

Eu não uso Windows então não sei exatamente o que você deve fazer para resolver. Eu tentaria desinstalar e instalar de novo e verificar se está na última versão (no momento `0.6`).

**Comment by diogobarreto** [comment]
Yes, Hugo, it was some version mishap, I uninstalled and reinstalled everything and the commands are working.  An only minor issue I have now is regarding the year and month parameters where, before, I would use %yyyy% for the current year and %mm% for the current month and this no longer works:

> C:\odrive\OneDrive\Documents\GitHub\guiabolso2csv>call guiabolso2csv --email email@email.com --year 2020 --month 01 --last-year %yyyy% --last-month %mm% --excel
Usage: guiabolso2csv [OPTIONS]
Try 'guiabolso2csv --help' for help.
Error: Invalid value for '--last-year': %yyyy% is not a valid integer

Thanks again for helping me out with this!
