### ISSUE TITLE
Campo de data

### ISSUE THREAD

**Issue by diogobarreto** [hugombarreto/guiabolso2csv#13]
Hugo,

Utilizando a função básica, reparei que o campo de data está vindo de forma incorreta.  Ele tem uma coerência entre as datas de um mesmo mês -- se dividir a diferença entre datas por 24x60x60x1000 (milisegundos) --, mas entre meses não achei um padrão.  Deve ser algum outro campo/código interno do site.  Se puder dar uma olhada nisso também, seria ótimo!

Muito obrigado por manter o projeto vivo, ele tem sido muito importante para arquivar minhas contas a cada 6m.  Desejo também um Feliz 2021!

**Comment by hsadok** [comment]
Oi Diogo, feliz 2021!

A data não é mais no formato UNIX como discutido em #1? Você pode me dar exemplos de algumas datas?

Obrigado!

**Comment by diogobarreto** [comment]
Hugo,

It was the same issue as #1, as you mentioned above -- can't believe I didn't recall and redid the analysis again!   It is still present in the CSV export and I only noticed because I wasn't managing to use the --excel parameter (now solved as well) and gave the CSV export a try.  If you still want some data examples, here they are:

> date Excel export | date CSV export
2020-12-31 | 1609383600000
2020-12-31 | 1609383600000
2020-12-30 | 1609297200000
2020-12-22 | 1608606000000
2020-12-22 | 1608606000000
2020-12-22 | 1608606000000
2020-12-22 | 1608606000000
2020-12-21 | 1608519600000
2020-12-21 | 1608519600000
2020-12-18 | 1608260400000
2020-12-17 | 1608174000000
2020-12-17 | 1608174000000



 Thanks again, Hugo!  (just noticed I switched my reply to English, sorry about that)

**Comment by hsadok** [comment]
Valeu pela resposta Diogo. Bom que está tudo funcionando agora!
