### ISSUE TITLE
EventNotFound

### ISSUE THREAD

**Issue by agneisilva** [hugombarreto/guiabolso2csv#14]
Ao solicitar uma extração apresenta eventNotFound

![image](https://user-images.githubusercontent.com/58611041/114640621-e37c2400-9ca6-11eb-81f4-3e6ac3225c11.png)

**Comment by hsadok** [comment]
Oi você está usando a versão antiga. Atualiza para a versão mais nova e vê se resolve:
```
pip install guiabolso2csv --upgrade
```
