### ISSUE TITLE
Issue running

### ISSUE THREAD

**Issue by diogobarreto** [hugombarreto/guiabolso2csv#3]
Hugo,
I don't know if you're still maintaing this, but I had an issue running GuiaBolso... it didn't run, giving multiple errors (printfile, then couldn't import guiabolso archive, etc...).   If you're still keeping this going, any help is much appreciated!
Kind rgds and happy new year,
Diogo

**Comment by hsadok** [comment]
Hi Diogo,

I'm currently on vacation and not actively maintaining this, but I do care if it works. Would you mind replying with a detailed output and the commands you used to install and run the program?

Moreover, what is your environment? Are you using Linux (if yes, what distro) or macOS?

Thank you very much for reporting this.

Happy new year!
Hugo

**Comment by diogobarreto** [comment]
Hi Hugo,

I tried to install the older version and the new version and, apparently, Python has updated some code references and there is a compilation error.  It installs perfectly, the requirements install as well, but I get an error code when I try to execute the guiabolso command:
 
![image](https://user-images.githubusercontent.com/11183703/55771739-aa799b00-5a5f-11e9-9397-cf88920d1c26.png)
 
This was a neat little exporter, would love to see it working again.

Kind rgds,

Diogo

**Comment by diogobarreto** [comment]
Hugo,
After fixing many parenthesis in the print commands in both ___main___ and guiabolso files (apparently a Python update), I manage to run the program, give my email address, password, year, month and then reach this standstill:
![image](https://user-images.githubusercontent.com/11183703/55772967-f5e27800-5a64-11e9-8fa6-234cb367d38a.png)

This is as far as my rudimentary knowledge can take me.

Kind rgds,

Diogo

**Comment by diogobarreto** [comment]
Hugo,

I managed to get it running for Python version 2.7.16.  Hence, it's compatibility with Python's 3+ command that was the issue.  If you could upgrade it sometime, looking ahead for a time without Python 2.7 (it was tricky to install PIP), that would be great. 

Thanks in advance, Hugo, and sorry for posting so many messages.

Kind rgds,

Diogo

**Comment by hsadok** [comment]
@diogobarreto Thank you for pointing that out and for taking the time to identify the issue! I have adapted the source code to work with python3. Hopefully this solves your problem.

Best,
Hugo
