### ISSUE TITLE
Criar lançamentos em conta manuais

### ISSUE THREAD

**Issue by osnipassos** [hugombarreto/guiabolso2csv#4]
Olá Hugo, parabéns pelo projeto. Voltei a usar o guiabolso e o seu aplicativo me ajuda muito.

Chegou a considerar alguma forma de criar lançamentos em conta manuais via script? 
Exemplo: importar um csv/ofx de uma conta não suportada.

Muito obrigado

**Comment by hsadok** [comment]
Oi Osni,
Obrigado! Não cheguei a pensar nisso. Você pensou em fazer tipo o contrário? Fazer upload de transações no computador para uma conta manual no GuiaBolso? Seria maneiro mesmo.

**Comment by osnipassos** [comment]
Bem melhor da maneira que você pensou.
Ter um csv/ofx e importar.

Isso é muito útil para contas não suportadas, de investimento, cartão alimentação etc.

**Comment by marlindo71** [comment]
Faala, @osnipassos 
Você ainda tem interesse nessa funcionalidade?

**Comment by osnipassos** [comment]
> Faala, @osnipassos
> Você ainda tem interesse nessa funcionalidade?

Opa, tenho sim. Tem uma ideia de como fazer?

**Comment by marlindo71** [comment]
Tenho. Da pra fazer na mesma vibe que o programa está buscando os dados.

Atualmente, ele envia uma requisição post com os dados da solicitação e o guiabolso retorna um json.

Pra fazer os lançamentos parece ser a mesma coisa. É só mandar a request com os dados sobre o lançamento.

![image](https://user-images.githubusercontent.com/9497924/81251195-16c72500-8ff9-11ea-98b4-a790c8ec2b5f.png)

Só não sei com ficaria o lance de ter um arquivo ofx como fonte dos dados. Mas vou dar uma pesquisada.

**Comment by marlindo71** [comment]
@osnipassos Eu fiz uma versão funcional do programa e coloquei num repositório separado.
Se quiser pode testar lá

https://github.com/marlindo71/csv2guiabolso

@hsadok Tem problema eu ter criado um outro repositório para fazer essa funcionalidade separado?
Como eu peguei praticamente tudo de exemplo do seu repositório, prefiro perguntar.

**Comment by hsadok** [comment]
Oi @marlindo71 não tem problema nenhum. Acho legal você ter implementado isso 🙂. Como a licença do guiabolso2csv é GPLv3, só peço que você copie o arquivo LICENSE.txt também para o seu repositório.

**Comment by hsadok** [comment]
Então vou fechar isso. Para quem estiver interessado em fazer upload de transações é só usar o https://github.com/marlindo71/csv2guiabolso

**Comment by osnipassos** [comment]
> @osnipassos Eu fiz uma versão funcional do programa e coloquei num repositório separado.
> Se quiser pode testar lá
> 
> https://github.com/marlindo71/csv2guiabolso
> 
> @hsadok Tem problema eu ter criado um outro repositório para fazer essa funcionalidade separado?
> Como eu peguei praticamente tudo de exemplo do seu repositório, prefiro perguntar.

Opa, vou testar!
