### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by osnipassos** [hugombarreto/guiabolso2csv#5]
Olá,

Nessa semana passou a dar esse erro ao tentar conectar com o Guiabolso.

Estava funcionando perfeitamente antes.
<img width="1440" alt="Screen Shot 2019-05-28 at 14 04 10" src="https://user-images.githubusercontent.com/711222/58497069-7febba80-8151-11e9-9b76-6268f85979ab.png">

**Comment by hsadok** [comment]
Oi Osni,

Parece que eles habilitaram um serviço que previne bots. Isso está impedindo que o `guiabolso2csv` funcione corretamente

<img width="798" alt="Screen Shot 2019-05-28 at 19 35 28" src="https://user-images.githubusercontent.com/3202037/58516889-e982bd80-817f-11e9-9a07-4dbe6bafabee.png">

Não sei se foi proposital para prevenir scraping como o do `guiabolso2csv` ou se foi por algum outro motivo. Vou ver se entro em contato com eles para obter mais informações.

**Comment by osnipassos** [comment]
Quase irônico eles fazerem isso não? Já que eles fazem a mesma coisa com os bancos.

Será que tem como deixar esse captcha para ser resolvido pelo usuário?

**Comment by hsadok** [comment]
> Quase irônico eles fazerem isso não? Já que eles fazem a mesma coisa com os bancos.

É mesmo haha. Mas não tenho certeza se fizeram isso com o intuito de bloquear o que o `guiabolso2csv` faz. 

> Será que tem como deixar esse captcha para ser resolvido pelo usuário?

Existem formas mais "agressivas" usando Selenium (acredito que o GuiaBolso use isso para acessar alguns bancos) mas é bem mais pesado e daria um bom trabalho extra.

Vou esperar uma resposta deles mas enquanto isso, este projeto está morto 😢

**Comment by hsadok** [comment]
Osni,

Me responderam. Segue parte da resposta:

> Atualmente nossa plataforma passou por mudanças de monitoramento e segurança e esse tipo de acesso foi bloqueado, por enquanto não conseguiremos apoiar ou contribuir com o seu projeto.

Uma pena...

**Comment by osnipassos** [comment]
Que pena.

Conversei com outra empresa que usa o Imperva. Eles recomendaram ao fazer colocar o User Agent como Chrome para passar (dai só pega por repetição).

Fica a dica

**Comment by diogobarreto** [comment]
Uma pena Hugo, fiquei 2 meses sem utilizar o programa e vejo essa triste notícia...  de qqr modo, obrigado pelo update para o Python 3.0 e tomara que esse serviço de autenticação seja superado.

Será que não teria como ter um "manual work-around", onde eu pudesse logar no GuiaBolso via o browser e daí rodaria o programa?

**Comment by leofac83** [comment]
Poxa infelizmente descobri o programa após o problema. 
Tenho um histórico grande de dados no guiabolso e estou procurando formas de baixar.

**Comment by lhmviola** [comment]
Pena, eu tb so descobri depois que foi bloqueado.

**Comment by marlindo71** [comment]
@lhmviola @leofac83 @diogobarreto @osnipassos Será que alguém consegue testar pra ver se a última atualização também resolveu este problema?

Conforme o @hsadok disse no outro tópico, é só atualizar pelo proprio pip

`pip install guiabolso2csv --upgrade`

**Comment by osnipassos** [comment]
Pessoal, testei aqui e funcionou perfeitamente.

Parabéns!

**Comment by diogobarreto** [comment]
Excelente, Marlindo, obrigado pelo fix, está funcionando perfeitamente.  Até voltei a usar o GuiaBolso!

> @lhmviola @leofac83 @diogobarreto @osnipassos Será que alguém consegue testar pra ver se a última atualização também resolveu este problema?
> 
> Conforme o @hsadok disse no outro tópico, é só atualizar pelo proprio pip
> 
> `pip install guiabolso2csv --upgrade`
