### ISSUE TITLE
"KeyError: 'errorMessage'" in setup test drive

### ISSUE THREAD

**Issue by Peridian** [hugombarreto/guiabolso2csv#6]
Olá!

Antes de mais nada, obrigado por fazer um projeto para isso!

Sobre o meu problema, eu simplesmente dei pip install, fiz o que o README fala e deu o erro a seguir

Abs!

------

Traceback (most recent call last):
  File "C:\Users\resource\AppData\Local\Programs\Python\Python38-32\Scripts\guiabolso2csv-script.py", line 11, in <module>
    load_entry_point('guiabolso2csv==0.4', 'console_scripts', 'guiabolso2csv')()
  File "C:\Users\resource\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\resource\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\resource\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\resource\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\resource\AppData\Local\Programs\Python\Python38-32\lib\site-packages\guiabolso2csv\__main__.py", line 40, in main
    gb = GuiaBolso(email, password)
  File "C:\Users\resource\AppData\Local\Programs\Python\Python38-32\lib\site-packages\guiabolso2csv\guia_bolso.py", line 54, in __init__
    self.login()
  File "C:\Users\resource\AppData\Local\Programs\Python\Python38-32\lib\site-packages\guiabolso2csv\guia_bolso.py", line 100, in login
    print(response['error']['errorMessage'])
KeyError: 'errorMessage'

**Comment by hsadok** [comment]
Oi Tuca,

Infelizmente algumas mudanças no GuiaBolso fizeram com que o programa deixasse de funcionar corretamente -- isso inclui um serviço que previne que mecanismos automáticos interajam com o aplicativo (#5).

Eu cancelei a minha conta e não consigo mais testar o programa. No entanto, caso você ou outra pessoa saiba alguma forma de corrigir o problema por favor sinta-se livre para submeter um patch 😀.

**Comment by marlindo71** [comment]
Faala, Hugo.

Primeiramente, parabéns pelo projeto.

Eu já estava procurando por uma solução dessas faz tempo. Na verdade eu já até tinha visto seu projeto alguns anos atrás.

Essa semana eu finalmente tentei utilizar o programa e vi que estava com esse erro.

Como estou aprendendo python, resolvi dar uma olhada.

Eu consegui resolver os erros utilizando as novas APIs do guiabolso.

Eu fiz um fork e ajustei lá.
Mandei um request tbm.
Como eu não sei utilizar o github, não sei se fiz da maneira correta.

Mas estou disposto a ajudar no projeto com o pouco de conhecimento que tenho.

**Comment by hsadok** [comment]
Obrigado Marlindo! Isso é de mais!

O código parece bom, como eu não tenho mais conta no guiabolso, não consigo testar. Será que alguém consegue dar uma olhada? @osnipassos @diogobarreto ?

**Comment by osnipassos** [comment]
Acredito que está ok, basta aprovar o PR

**Comment by hsadok** [comment]
Pronto. Podem atualizar com:
```
pip install guiabolso2csv --upgrade
```

Obrigado de novo @marlindo71 !

**Comment by diogobarreto** [comment]
Caros,
Havia abandonado o GuiaBolso, mas reinstalei ele aqui para experimentar.  Infelizmente, sigo tendo o mesmo problema, não sei o que posso estar fazendo de errado.  Alguma ideia, @marlindo71?

> Traceback (most recent call last):
  File "C:\Program Files\Python\Python37\Scripts\guiabolso2csv-script.py", line 11, in <module>
    load_entry_point('guiabolso2csv==0.4', 'console_scripts', 'guiabolso2csv')()
  File "c:\program files\python\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files\python\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\program files\python\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files\python\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\program files\python\python37\lib\site-packages\guiabolso2csv\__main__.py", line 40, in main
    gb = GuiaBolso(email, password)
  File "c:\program files\python\python37\lib\site-packages\guiabolso2csv\guia_bolso.py", line 54, in __init__
    self.login()
  File "c:\program files\python\python37\lib\site-packages\guiabolso2csv\guia_bolso.py", line 100, in login
    print(response['error']['errorMessage'])
KeyError: 'errorMessage'

**Comment by hsadok** [comment]
Isso parece a versão antiga, você atualizou?

**Comment by diogobarreto** [comment]
> Isso parece a versão antiga, você atualizou?

Também me pareceu, Hugo, logo eu até renomeei o diretório e dei um fresh clone do GitHub, mas esse erro persistiu.
Antes de fazer isso, eu havia executado o comando de upgrade com sucesso.
Existiria alguma info adicional que eu poderia fornecer para esclarecer melhor a questão?

**Comment by marlindo71** [comment]
@diogobarreto se vc der um `pip show guiabolso2csv` mostra qual versão?

![image](https://user-images.githubusercontent.com/9497924/82465767-0487c500-9a96-11ea-8a14-9ea2f38d4d44.png)

**Comment by diogobarreto** [comment]
> @diogobarreto se vc der um `pip show guiabolso2csv` mostra qual versão?
> 
> ![image](https://user-images.githubusercontent.com/9497924/82465767-0487c500-9a96-11ea-8a14-9ea2f38d4d44.png)

@marlindo71 segue a minha versão:
![image](https://user-images.githubusercontent.com/11183703/82467429-094d7880-9a98-11ea-88f1-02ef5fec7910.png)

**Comment by marlindo71** [comment]
@diogobarreto
Rapaz, eu to achando que tem alguma treta no local que o python ta executando o programa.

Quanto vc dá o show, o Location ta em `c:\users\diogo.barreto\appdata\roaming\python\python37\site-packages`.

Mas quando vc executa, o erro ta dizendo que é no arquivo que ta em outra pasta.

`File "c:\program files\python\python37\lib\site-packages\guiabolso2csv\guia_bolso.py", line 100, in` 

To achando que a atualização ta instalada no appdata\roaming e a versão antiga ta no program files.

Faz um teste, vai nesse arquivo e compara o que ta nas duas pastas.

`c:\users\diogo.barreto\appdata\roaming\python\python37\site-packages\guiabolso2csv\guia_bolso.py`

`c:\program files\python\python37\lib\site-packages\guiabolso2csv\guia_bolso.py`

Vê se a linha 100 dos dois tá igual.

Esse é o da última versão:

![image](https://user-images.githubusercontent.com/9497924/82471098-9eeb0700-9a9c-11ea-877d-aeaea8986088.png)

**Comment by diogobarreto** [comment]
> c:\users\diogo.barreto\appdata\roaming\python\python37\site-packages\guiabolso2csv\guia_bolso.py

@marlindo71 great catch!   de fato, ele atualizou no appdata\roaming, mas não no outro endereço... vou verificar como remover essas duas instâncias, para ficar com uma apenas.  Assim que o fizer, testo e volto a comentar aqui.  Obrigado aí pelo debugging remoto!

**Comment by diogobarreto** [comment]
> @diogobarreto
> Rapaz, eu to achando que tem alguma treta no local que o python ta executando o programa.
> 
> Quanto vc dá o show, o Location ta em `c:\users\diogo.barreto\appdata\roaming\python\python37\site-packages`.
> 
> Mas quando vc executa, o erro ta dizendo que é no arquivo que ta em outra pasta.
> 
> `File "c:\program files\python\python37\lib\site-packages\guiabolso2csv\guia_bolso.py", line 100, in`
> 
> To achando que a atualização ta instalada no appdata\roaming e a versão antiga ta no program files.
> 
> Faz um teste, vai nesse arquivo e compara o que ta nas duas pastas.
> 
> `c:\users\diogo.barreto\appdata\roaming\python\python37\site-packages\guiabolso2csv\guia_bolso.py`
> 
> `c:\program files\python\python37\lib\site-packages\guiabolso2csv\guia_bolso.py`
> 
> Vê se a linha 100 dos dois tá igual.
> 
> Esse é o da última versão:
> 
> ![image](https://user-images.githubusercontent.com/9497924/82471098-9eeb0700-9a9c-11ea-877d-aeaea8986088.png)

@marlindo71  removi a segunda instalação do Python, rodei os comandos e funcionou like a charm!   Obrigado por esse bug fix, acabei de voltar a utilizar o guiabolso!
