### ISSUE TITLE
Utilização de selenium

### ISSUE THREAD

**Issue by mscampos92** [hugombarreto/guiabolso2csv#7]
Não sei como está sua intenção de continuar com o projeto mas acredito que com selenium seria possível resolver essa "validação".

Abs.

**Comment by marlindo71** [comment]
@mscampos92 Teve uma nova atualização no programa. A principio não foi necessário a utilização do selenium.

Se puder testar, ficaríamos agradecidos.

`pip install guiabolso2csv --upgrade`
