### ISSUE TITLE
Trazer a data 

### ISSUE THREAD

**Issue by luxu** [hugombarreto/guiabolso2csv#9]
Amigo sensacional sua raspagem e veio a meu ajudar muito, mas as datas estão num formato que não é timestamp, como consigo pegar as datas certas?

**Comment by hsadok** [comment]
Oi Luciano obrigado! Dá uma olhada em #1 e me fala se isso resolve o seu problema.

**Comment by luxu** [comment]
Perfeitamente só jogar pra saída pro excel q resolveu....vou implementar o pysimplegui e deve ficar show...
